FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

RUN pip install playwright
RUN playwright install --with-deps

COPY . .

CMD ["pytest", "--headless", "--alluredir=allure-results"]